class Config:
    CAMERA = False
    GHOST = False

    SCREEN_WIDTH = 240
    SCREEN_CAMERA_WIDTH = 480
    SCREEN_HEIGHT = 240

    CAMERA_VIEW_WIDTH = 200
    CAMERA_VIEW_HEIGHT = 200

    CAMERA_WIDTH = 320
    CAMERA_HEIGHT = 240

    DEMO_IDLE_SEC = 120